language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - export CODECOV_TOKEN="cd374ecb-a4c5-4473-8cea-4cc0d2c8f6fa"
  - bash <(curl -s https://codecov.io/bash)

branches:
  - develop