language: java

notifications:
  email: false

script:
  - mvn clean package -DskipTests=true
  - mvn cobertura:cobertura

branches:
  - develop

after_success:
- bash <(curl -s https://codecov.io/bash)
